charset utf-8;

server {
    listen 80;
    server_name _; # ALB를 통해 들어오므로 모든 호스트 허용

    # 클라이언트 실제 IP 및 프로토콜 전달 설정
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto; # ALB가 보낸 프로토콜(https) 전달

    # 1. 프론트엔드 정적 파일
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. FastAPI 백엔드 프록시
    location /api/ {
        # proxy_pass 경로 설정 끝을 /로 끝낼 결우 /api를 제외한 이후 경로만 FastAPI로 전달합니다.
        # 예) 요청 경로: /api/users -> FastAPI 경로: /users
        proxy_pass http://my-app:8000/;
        proxy_http_version 1.1;

        # 필수 프록시 헤더 ============================================================
        # 1. 클라이언트가 요청한 원래의 호스트(도메인 또는 IP:포트) 정보를 백엔드에 전달합니다.
        proxy_set_header Host $host;

        # 2. 프록시를 거치기 전, 요청을 보낸 실제 클라이언트의 IP 주소를 전달합니다.
        proxy_set_header X-Real-IP $remote_addr;

        # 3. 클라이언트가 Nginx에 도달하기까지 거쳐간 모든 프록시 및 로드밸런서의 IP 목록을 누적하여 전달합니다.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 4. 클라이언트가 서버에 접속할 때 사용한 프로토콜(http 또는 https) 정보를 전달합니다.
        proxy_set_header X-Forwarded-Proto $scheme;

        # 5. 연결유지 최적화: 백엔드와의 지속 연결을 위해 Connection 헤더 제거 (keep-alive 활성화)
        proxy_set_header Connection "";

        # 선택 속성 ======================================================================
        proxy_read_timeout 60s;
    }
}