# 워크플로우 이름
name: GitOps ArgoCD CI/CD Pipeline

on:
  push:
    branches:
      - main  # 트리거 설정: main 브랜치에 푸쉬될 때 실행

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # runs-on에 정의된 서버가 깃에 업로드된 파일을 수정할 수 있도록 함(deployment.yaml의 image 태그 자동 수정)
    steps:
    - name: 소스코드 체크아웃 # 깃에 push된 파일을 서버로 복사
      uses: actions/checkout@v4
    
    - name: Docker Hub 로그인
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Docker 이미지 빌드 및 푸쉬
      uses: docker/build-push-action@v5
      with:
        context: ./nginx
        file: ./nginx/Dockerfile  # Dockerfile의 경로 및 파일명
        push: true
        tags: minseung12/nginx:${{ github.sha }} # (중요) 이미지명 정의, 태그 자동생성

    - name: 쿠버네티스 파일의 이미지 태그 갱신 및 Git push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        sed -i 's|image: minseung12/nginx:.*|image: minseung12/nginx:${{ github.sha }}|g' ./k8s/deployment.yaml

        git add ./k8s/deployment.yaml
        git commit -m "Deployment file tag Update(${{ github.sha }})"
        git push